BEGIN;

CREATE TABLE ai_summaries
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    summary_code VARCHAR(20) NOT NULL,

    ai_analysis_id UUID NOT NULL,

    summary_type VARCHAR(30) NOT NULL DEFAULT 'EXECUTIVE',

    title VARCHAR(250),

    summary TEXT NOT NULL,

    strengths TEXT,
    weaknesses TEXT,
    opportunities TEXT,
    risks TEXT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_ai_summary_code
        UNIQUE(summary_code),

    CONSTRAINT fk_ai_summary_analysis
        FOREIGN KEY(ai_analysis_id)
        REFERENCES ai_analysis(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_summary_type
        CHECK
        (
            summary_type IN
            (
                'EXECUTIVE',
                'TECHNICAL',
                'MARKETING',
                'TRADE',
                'CUSTOM'
            )
        )
);

COMMENT ON TABLE ai_summaries IS
'Natural language summaries generated by AI.';

COMMIT;
