BEGIN;

CREATE TABLE ai_recommendations
(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    recommendation_code VARCHAR(20) NOT NULL,

    ai_analysis_id UUID NOT NULL,

    recommendation_type VARCHAR(50) NOT NULL,

    priority VARCHAR(20) DEFAULT 'MEDIUM',

    recommendation TEXT NOT NULL,

    rationale TEXT,

    confidence_score SMALLINT,

    is_accepted BOOLEAN,

    accepted_at TIMESTAMPTZ,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_ai_recommendation_code
        UNIQUE(recommendation_code),

    CONSTRAINT fk_ai_recommendation_analysis
        FOREIGN KEY(ai_analysis_id)
        REFERENCES ai_analysis(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_priority
        CHECK
        (
            priority IN
            (
                'LOW',
                'MEDIUM',
                'HIGH',
                'CRITICAL'
            )
        ),

    CONSTRAINT chk_recommendation_confidence
        CHECK
        (
            confidence_score BETWEEN 0 AND 100
        )
);

COMMENT ON TABLE ai_recommendations IS
'Business recommendations generated by AI.';

COMMIT;
